services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    links:
      - mysql
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=piztak
      - DB_USERNAME=root
      - DB_PASSWORD=root
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: piztak
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
